version: '3.1'
services:
  ui:
    image: owncloud
    ports:
      - 8080:80
    volumes:
      - data:/var/www/html

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - mysql:/var/lib/mysql

volumes:
    data:
    mysql:
